### ISSUE TITLE
Error during self sign certificate generation

### ISSUE THREAD

**Issue by mmoioli** [marcinotorowski/MSIX-Hero#98] opened 2021-02-17 14:17 UTC
![1](https://user-images.githubusercontent.com/58217723/108216872-3c11c380-7133-11eb-9548-9cb2252ca0ab.jpg)

**Comment by marcinotorowski** [comment] 2021-02-17 17:48
Hi @mmoioli, thanks for spotting and reporting this. The problem is a regression after migration to .NET 5.0, and is caused by the following line:

https://github.com/marcinotorowski/MSIX-Hero/blob/029f6c443bfb812c9e05227d8740c5262c23d1e1/src/Otor.MsixHero.Infrastructure/ThirdParty/PowerShell/PowerShellSession.cs#L110

This parameter is only required for `Appx` module, but must not be used for `PKI` (to which for example `Export-Certificate` belongs to). This must be fixed, as it also affects some other modules.

**Comment by marcinotorowski** [comment] 2021-02-17 17:50
Resolved in https://github.com/marcinotorowski/MSIX-Hero/commit/4c2735ec7168a139454b56260826d58db9671b00

**Closed** 2021-02-17 17:50 UTC
Labels: bug

**Comment by marcinotorowski** [comment] 2021-02-17 18:58
Available in preview build:
https://github.com/marcinotorowski/MSIX-Hero/releases/tag/v2.0.68-pre
