### ISSUE TITLE
Error preparing volume for app attach

### ISSUE THREAD

**Issue by apbaseball** [marcinotorowski/MSIX-Hero#118] opened 2021-06-10 15:32 UTC
Trying to create a volume for app attach throws an error:
"MSIX Hero - Error
Successfully started the Shell Hardware Detection Service"

![image](https://user-images.githubusercontent.com/24400452/121553607-6a1b5c00-c9df-11eb-989c-ffc7448fd141.png)

**Comment by marcinotorowski** [comment] 2021-06-13 21:37
Most likely this is an issue with parsing of the error returned by Microsoft tool msixmgr.exe. I did a test commit in which the parsing logs some more information (and tries to exclude this line). Additionally, it is now possible to show detailed logs which may help with troubleshooting.

Get the test build (digitally signed) from
https://msixhero.net/alfa/msix-hero-2.2.7.0.msix

Go to settings and in the tab OTHER activate verbose logs (this is new in 2.2.7, you will not find this setting in the last official release build)
![image](https://user-images.githubusercontent.com/22944216/121822505-b399ce80-cc9f-11eb-8d9c-2b98981710f3.png)

In the software list, right click MSIX Hero and press Open user folder
![image](https://user-images.githubusercontent.com/22944216/121822566-0a070d00-cca0-11eb-8252-92ed98ffc60b.png)

This will open Explorer with the default log location.

Now repeat the app attach stuff, and observe which logs are written. You can also send them here for analysis. The relevant part will be probably in the log for UAC helper.

**Comment by LukePly** [comment] 2021-09-06 13:30
Hello Marcin,
attaching my log I have exactly the same.. 
[20210906-031621_msixhero-uac_Trace.log](https://github.com/marcinotorowski/MSIX-Hero/files/7116269/20210906-031621_msixhero-uac_Trace.log)

**Comment by marcinotorowski** [comment] 2021-09-06 18:09
This may be only a best guess, as the log from msixmgr does not contain anything more specific than the denial of access. Could this be that an antivirus kicked in and locked the file, preventing the VHD from being formatted? Is this happening on a physical device, or also in a virtual / sandbox environment?

**Comment by LukePly** [comment] 2021-09-07 06:45
It's not antivirus this is clean virtual msix environment - (hyperV). 
Any other suggestion?

**Comment by LukePly** [comment] 2021-09-08 10:21
Command without msix hero is working good - but it seems like window with error info from your app is breaking creation of vhd process. 
![image](https://user-images.githubusercontent.com/90198904/132492412-3b68240b-049f-419c-8494-391b1f981f69.png)

**Comment by marcinotorowski** [comment] 2021-09-08 21:15
The window just grabs the output of msixmgr in case of a non-zero exit code which is considered to be a failed exit code. Could you send a new log or is it the same issue for which has been already provided (`Formatting the disk failed with error code: 3`)?

**Comment by marcinotorowski** [comment] 2021-09-09 21:37
I found the issue, msixmgr cannot be run from MSIX, because its working directory is read-only. The change is in the following commit 121b441862eba04f6711465ccce26cad13f3170c.

Try out the following build: http://msixhero.net/msix-hero-2.2.24.0.msix

This version is not yet public.

**Comment by LukePly** [comment] 2021-09-10 05:55
Hi Marcin,
I can confirm that the latest version is working as should. Thanks!

**Comment by marcinotorowski** [comment] 2021-09-10 20:19
Fixed in release 2.2.29. The issue will be closed.

- https://msixhero.net/redirect/release-notes/2.2.29
- https://github.com/marcinotorowski/MSIX-Hero/releases/tag/v2.2.29

**Closed by marcinotorowski** 2021-09-10 20:19 UTC
